const {
  CLIENT_REGISTER_NAME,
  CLIENT_REGISTER_SERVER_PORT,
  CLIENT_REGISTER_DATABASE_URL,
  CLIENT_REGISTER_REDIS_URL,
  KAFKA_CLIENT_TOPIC,
  KAFKA_BROKER_URL
} = process.env

if (!CLIENT_REGISTER_DATABASE_URL) {
  throw new Error('Missing environment variable: CLIENT_REGISTER_DATABASE_URL')
}

if (!CLIENT_REGISTER_REDIS_URL) {
  throw new Error('Missing environment variable: CLIENT_REGISTER_REDIS_URL')
}

if (!KAFKA_BROKER_URL) {
  throw new Error('Missing environment variable: KAFKA_BROKER_URL')
}

const env = {
  APP_NAME: CLIENT_REGISTER_NAME ?? 'client-register',
  SERVER_PORT: parseInt(CLIENT_REGISTER_SERVER_PORT ?? '3000', 10),
  DATABASE_URL: CLIENT_REGISTER_DATABASE_URL,
  REDIS_URL: CLIENT_REGISTER_REDIS_URL,
  CLIENT_TOPIC: KAFKA_CLIENT_TOPIC ?? 'client',
  KAFKA_BROKER_URL: KAFKA_BROKER_URL
}

export { env }
